name: Backup every 5 minutes

on:
    schedule:
        - cron: "*/5 * * * *"
jobs:
  backup:
    runs-on: backup-runner
    # Map a step output to a job output
    outputs:
      -U : ${{secrets.PG_USER}}
      --password : ${{secrets.PG_PASS}}
      -h : ${{secrets.PG_HOST}}
      -p : ${{secrets.PG_PORT}}
      MEDIA_BUCKET_NAME : ${{secrets.MEDIA_BUCKET_NAME}}
      BUCKET_S3_SERVER : ${{secrets.BUCKET_S3_SERVER}}
      ACCESS_KEY_SECRET : ${{secrets.ACCESS_KEY_SECRET}}
      ACCESS_KEY_ID : ${{secrets.ACCESS_KEY_ID}}
    steps:
    - id: step1
      run: pg_dump -h ${secrets.PG_HOST} -d handbook -Ft -f aaa.tar
    - id: step2
      run: echo "STEP 2"
  upload:
    runs-on: backup-runner
    needs: backup
    steps:
    - run: echo "--"
