name: Backup every 3 minutes

on:
    schedule:
        - cron: "*/3 * * * *"
jobs:
  job1:
    runs-on: backup-runner
    # Map a step output to a job output
    outputs:
      -U : ${{secrets.PG_USER}}
      --password : ${{secrets.PG_PASS}}
      -h : ${{secrets.PG_HOST}}
      -p : ${{secrets.PG_PORT}}
      MEDIA_BUCKET_NAME : ${{secrets.MEDIA_BUCKET_NAME}}
      BUCKET_S3_SERVER : ${{secrets.BUCKET_S3_SERVER}}
      ACCESS_KEY_SECRET : ${{secrets.ACCESS_KEY_SECRET}}
      ACCESS_KEY_ID : ${{secrets.ACCESS_KEY_ID}}
    steps:
    - id: step1
      run: pg_dump -d handbook 
    - id: step2
      run: echo "STEP 2"
  job2:
    runs-on: backup-runner
    needs: job1
    steps:
    - run: echo ${{needs.job1.outputs.-U}} ${{needs.job1.outputs.--password}}
