name: Backup every 5 minutes

on:
    schedule:
        - cron: "*/5 * * * *"
jobs:
  build:
    runs-on: backup-runner
    shell: bash
    steps:
    - run: pg_dump -d handbook 
    with    :
      -U : ${{secrets.PG_USER}}
      --password : ${{secrets.PG_PASS}}
      -h : ${{secrets.PG_HOST}}
      -p : ${{secrets.PG_PORT}}
      MEDIA_BUCKET_NAME : ${{secrets.MEDIA_BUCKET_NAME}}
      BUCKET_S3_SERVER : ${{secrets.BUCKET_S3_SERVER}}
      ACCESS_KEY_SECRET : ${{secrets.ACCESS_KEY_SECRET}}
      ACCESS_KEY_ID : ${{secrets.ACCESS_KEY_ID}}
