name: Backup every 5 minutes

on:
    schedule:
        - cron: "*/5 * * * *"
jobs:
  build:
    runs-on: backup-runner
    steps:
    - run: PGPASSWORD=$DB_PASS pg_dump -h $DB_HOST --dbname handbook -p $DB_PORT -U $DB_USER -Ft -f handbook-$(date +'%Y-%m-%d-%H').tar
    env:
      DB_USER : ${{secrets.PG_USER}}
      DB_PASS : ${{secrets.PG_PASS}}
      DB_HOST : ${{secrets.PG_HOST}}
      MEDIA_BUCKET_NAME : ${{secrets.MEDIA_BUCKET_NAME}}
      BUCKET_S3_SERVER : ${{secrets.BUCKET_S3_SERVER}}
      ACCESS_KEY_SECRET : ${{secrets.ACCESS_KEY_SECRET}}
      ACCESS_KEY_ID : ${{secrets.ACCESS_KEY_ID}}
      DB_PORT : ${{secrets.PG_PORT}}
