# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ digitalocean ]
  pull_request:
    branches: [ digitalocean ]

jobs:
  build:

    runs-on: docs.plus

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - run: DB_TYPE=mongodb DB_HOST="$MONGO_HOST" DB_PORT="27017" DB_USER="$MONGO_USERNAME" DB_PASS="$MONGO_PASSWORD" DB_NAME="doc" npm start
    env:
      MONGO_USERNAME : ${{ secrets.MONGO_USERNAME }}
      MONGO_PASSWORD : ${{ secrets.MONGO_PASSWORD }}
      MONGO_HOST : ${{ secrets.MONGO_HOST }}
