# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ digitalocean ]
  pull_request:
    branches: [ digitalocean ]

jobs:
  build:
    runs-on: docs.plus
    strategy:
      matrix:
        node-version: [10.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm run build --if-present
  run:
    runs-on: docs.plus
    strategy:
      matrix:
        node-version: [10.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: node ./node_modules/ep_etherpad-lite/node/server.js
    env:
      DB_USER : ${{secrets.MONGO_USERNAME}}
      DB_PASS : ${{secrets.MONGO_PASSWORD}}
      DB_HOST : ${{secrets.MONGO_HOST}}
      DB_TYPE : mongodb
      DB_PORT : 27017
      DB_NAME : docs