# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on: push 
    
jobs:
  build:
    runs-on: docs.plus
    strategy:
      matrix:
        node-version: [10.x]
    steps:
    - uses: actions/checkout@v2
    - uses: nelonoel/branch-name@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm run build --if-present
    - run: npm run deploy --if-present
    - run: DB_NAME=${BRANCH_NAME} pm2 start ecosystem.config.js --only ${BRANCH_NAME}
    env:
      DB_USER : ${{secrets.MONGO_USERNAME}}
      DB_PASS : ${{secrets.MONGO_PASSWORD}}
      DB_HOST : ${{secrets.MONGO_HOST}}
      MEDIA_BUCKET_NAME : ${{secrets.MEDIA_BUCKET_NAME}}
      BUCKET_S3_SERVER : ${{secrets.BUCKET_S3_SERVER}}
      ACCESS_KEY_SECRET : ${{secrets.ACCESS_KEY_SECRET}}
      ACCESS_KEY_ID : ${{secrets.ACCESS_KEY_ID}}
      DB_TYPE : mongodb
      DB_PORT : 27017
      
